[package]
name = "loader"
version = "0.1.0"
authors = ["Brenden Matthews <brenden@diddyinc.com>"]
edition = "2018"

[dependencies]
data-encoding = "2"
env_logger = "0.6"
failure = "0.1"
log = "0.4"
redis = "0.11"
reqwest = "0.9"
sodiumoxide = "0.2"
url = "2.0"
