version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - brndnmtthws
  ignore:
  - dependency-name: tokio
    versions:
    - 1.1.1
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: serde_derive
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
    - 1.0.63
- package-ecosystem: cargo
  directory: "/lib"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - brndnmtthws
- package-ecosystem: cargo
  directory: "/tools/loader"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - brndnmtthws
  ignore:
  - dependency-name: env_logger
    versions:
    - 0.8.2
