CREATE TABLE clients (
  id BIGSERIAL PRIMARY KEY,
  uuid UUID UNIQUE NOT NULL DEFAULT uuid_generate_v4 (),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  full_name TEXT NOT NULL,
  password_verifier BYTEA NOT NULL,
  password_salt BYTEA NOT NULL,
  phone_number TEXT NOT NULL UNIQUE,
  box_public_key TEXT NOT NULL,
  signing_public_key TEXT NOT NULL,
  profile TEXT,
  handle TEXT UNIQUE,
  handle_lowercase TEXT UNIQUE,
  phone_sms_verified BOOLEAN NOT NULL DEFAULT FALSE)
