[package]
name = "rolodex"
version = "0.1.0"
authors = ["Brenden Matthews <brenden@brndn.io>"]

[dependencies]
rolodex-grpc = { path = "lib"}
chrono = { version = "0.4"  }
diesel = { version = "1.4.2", features = ["postgres", "chrono"] }
env_logger = { version = "0.5", default-features = false }
futures = "0.1"
http = "0.1"
lazy_static = "1.3"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
tokio = "0.1"
tokio-rustls = "0.9"
color-backtrace = "0.1"
toml = "0.5"
tower-h2 = { git = "https://github.com/tower-rs/tower-h2" }
tower-grpc = { git = "https://github.com/tower-rs/tower-grpc" }
tower-request-modifier = { git = "https://github.com/tower-rs/tower-http" }
tower-service = "0.2"
tower-util = { git = "https://github.com/tower-rs/tower" }
uuid = { version = "0.7" }
yansi = "0.5"
