[service]
worker_threads = 4
ca_cert_path = "test/UmpyreAuth.crt"
tls_cert_path = "test/Rolodex.crt"
tls_key_path = "test/Rolodex.key"
bind_to_addr = "127.0.0.1:10011"

[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
connection_pool_size = 10

[metrics]
bind_to_address = "127.0.0.1:5000"
